### ISSUE TITLE
Проверка платежа

### ISSUE THREAD

**Issue by ilya-nikolaev** [nikitalm8/anypay#2]
Привет! Отличная работа!

У меня возник вопрос, как я могу проверить платеж? В документации написано, что приходит уведомление на сервер, но как я понимаю, здесь это не реализовано, поэтому нужно самостоятельно с каким-то периодом запрашивать данные о платеже методом payments. Я все верно понимаю? Заранее спасибо большое за разъяснения!

**Comment by nikitalm8** [comment]
Можно проверить платеж через get_payments, либо настроив url оповещения в ЛК anypay.
